# Generated by Django 5.0.6 on 2024-06-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_product_picture_url_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
