# Generated by Django 5.0.6 on 2024-06-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
