# Generated by Django 5.0.6 on 2024-06-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_user_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
